spring:
  application:
    name: swagger-service

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/swag?user=root
    username: root
    password: root
    initialization-mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none

server:
  port: 8083

swag:
  service:
    url: http://localhost:8081/

swagger:
  service:
    url: http://localhost:8082/