spring:
  application:
    name: swagger-service

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  data:
    mongodb:
      database: Cluster0
      uri: mongodb+srv://saiannam:QbMf0GRbWc662ofD@cluster0.zq8sjqk.mongodb.net/?retryWrites=true&w=majority

server:
  port: 8082

swag:
  service:
    url: http://localhost:8081/

swaggest:
  service:
    url: http://localhost:8083/